### PR TITLE
Adding basic auth for service endpoint

### PR DESCRIPTION
**Pull request by hkousha**

### CODE REVIEW

**Comment by hkousha** [comment]
Let me know what you think about this, if okay I ll go ahead and update the README file.

**Comment by palmerabollo** [comment]
Thanks for your contribution @hkousha. Please, go ahead and update the README file.

**Comment by palmerabollo** [comment]
@javierprovecho LGTM, could you please review the gin part, too?

**Comment by palmerabollo** [comment]
New release 1.3.0 & docker image published.

**Comment by hkousha** [comment]
Thanks guys,

**Pull request merged**
